### ISSUE TITLE
Changes in twitter archive

### ISSUE THREAD

**Issue by alarno** [cachuco/Delete-tweets-script---Google-apps-script#2]
Hi, twitter changed from tweets.csv to tweet.js, a json file...there is a way to still use your wonderfull script??

**Comment by cachuco** [comment]
Oh, I didn't know the change, I check for an update.  Thanks for the warning

**Comment by cachuco** [comment]
Updated the code to use the js file from the twitter archive.

**Comment by alarno** [comment]
great!!! very usefull
